name: 'Hello World Composite Action'
description: 'Greet someone and set a random number output'
inputs:
  who-to-greet:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: 'A random number'
runs:
  using: 'composite'
  steps:
    - name: Print greeting
      shell: bash  # Specify the shell
      run: echo "Hello ${{ inputs.who-to-greet }}"

    - name: Set random number output
      id: random
      shell: bash  # Specify the shell
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

    - name: Print random number
      shell: bash
      run: echo "Random number is ${{ steps.random.outputs.random-number }}"
