const fs = require('fs');
const path = require('path');

// Output directory for generated files
const outputDir = path.join(__dirname, 'dist');

// Ensure the directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir);
}

// Generate a simple output file
const outputFile = path.join(outputDir, 'output.txt');
fs.writeFileSync(outputFile, 'This is a test file generated by the Node.js application.\n');

console.log(`Generated file: ${outputFile}`);
