name: Workflow Commands Example

on:
  workflow_dispatch:

jobs:
  demonstrate_commands:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Demonstrate debug, notice, warning, and error messages
      - name: Set workflow messages
        run: |
          echo "::debug::This is a debug message"
          echo "::notice::This is a notice message"
          echo "::warning::This is a warning message"
          echo "::error::This is an error message"

      # Group log lines
      - name: Group log messages
        run: |
          echo "::group::Grouped logs start"
          echo "This is a grouped log line 1"
          echo "This is a grouped log line 2"
          echo "::endgroup::Grouped logs end"

      # Mask a value in logs
      - name: Mask sensitive values
        run: |
          echo "::add-mask::sensitive_value"
          echo "The value 'sensitive_value' will be masked in logs"

      # Stop and start workflow commands
      - name: Stop and start workflow commands
        run: |
          echo "::stop-commands::pause"
          echo "This will not appear in logs due to the stop command"
          echo "::pause::"

      # Send values to pre and post actions
      - name: Pre and post action setup
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Some values for pre/post actions setup"

      # Use environment files
      - name: Set environment variables
        run: |
          echo "MY_VAR=Hello, world!" >> $GITHUB_ENV
          echo "Set MY_VAR as an environment variable"

      # Set output parameters
      - name: Set output parameters
        id: set_output
        run: |
          echo "output_var=Action complete" >> $GITHUB_ENV
          echo "::set-output name=my_output::Action completed successfully"

      # Add a job summary
      - name: Add job summary
        run: echo "### Job Summary" >> $GITHUB_STEP_SUMMARY

      # Add a system path
      - name: Add system path
        run: |
          echo "/path/to/tool" >> $GITHUB_PATH
          echo "Added '/path/to/tool' to the system PATH"

      # Use output in another step
      - name: Use output from previous step
        run: |
          echo "Using the output: ${{ steps.set_output.outputs.my_output }}"
