name: Docker Action

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker action
      uses: ./action.yml
      with:
        who-to-greet: 'Mona the Octocat'
